// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4cMl2m7vBMQihv_5PUDw501tabitDAX0',
    appId: '1:682980829056:web:708513ce90c1cc790ec365',
    messagingSenderId: '682980829056',
    projectId: 'spotify42',
    authDomain: 'spotify42.firebaseapp.com',
    storageBucket: 'spotify42.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfm9uFT8d7o6zZZoACH7tl70wkvtR4x-c',
    appId: '1:682980829056:android:7450cec746ec84ac0ec365',
    messagingSenderId: '682980829056',
    projectId: 'spotify42',
    storageBucket: 'spotify42.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiW5kLH4X8CKbj2aQTcjtnXCdVS0h6mhY',
    appId: '1:682980829056:ios:4791b71171e121fa0ec365',
    messagingSenderId: '682980829056',
    projectId: 'spotify42',
    storageBucket: 'spotify42.firebasestorage.app',
    iosBundleId: 'com.example.refreshFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiW5kLH4X8CKbj2aQTcjtnXCdVS0h6mhY',
    appId: '1:682980829056:ios:4791b71171e121fa0ec365',
    messagingSenderId: '682980829056',
    projectId: 'spotify42',
    storageBucket: 'spotify42.firebasestorage.app',
    iosBundleId: 'com.example.refreshFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4cMl2m7vBMQihv_5PUDw501tabitDAX0',
    appId: '1:682980829056:web:6dd9b47340cb079c0ec365',
    messagingSenderId: '682980829056',
    projectId: 'spotify42',
    authDomain: 'spotify42.firebaseapp.com',
    storageBucket: 'spotify42.firebasestorage.app',
  );
}
